name: CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - run: pip3 install -r requirements.txt
      - run: python3 -m pytest
